sudo: required
services:
  - docker
before_install:
  # Install Google Cloud SQK CLI
  ## Get the encryted JSON file containing my sensitive information to access to my Google Cloud account
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  ## curl https://sdk.cloud.google.com === Download Google Cloud
  ## bash > /dev/null; === Install it locally on our instance that is assigned to us by Travis
  - curl https://sdk.cloud.google.com | bash > /dev/null;

  ## means that there is some configuration that's going to modify our shell inside of Travis-CI inside this file
  ## and we're going to apply that additional configuration through the source command.
  - source $HOME/google-cloud-sdk/path.bash.inc

  ## Install & update kubectl inside Travis environment
  - gcloud components update kubectl

  # Configure the SDK with out Google Cloud authentication information
  ## "service-account.json" = file containing information to access Google account
  - gcloud auth activate-service-account --key-file service-account.json
# Login to Docker CLI

# Build the "test" version of multi-client

# Run tests

# If tests are successful, run a script to deploy the newest images

# Build all our images, tag each one, push each to Docker Hub

# Apply all configuration files in "k8s" folder

# Imperatively set latest images on each deployment

