############################################################################
#########################         TEMPLATE         #########################
# To be used ONLY IF you want to configure your kubernetes environment WITH HTTPS CONNECTION
# /!\ This configuration requires A PAID DOMAIN NAME  /!\

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: yourdomain-com-tls
spec:
  secretName: yourdomain-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    commonName: yourdomain.com
    dnsNames:
      - yourdomain.com
      - www.yourdomain.com
