apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: worker
  template:
    metadata:
      labels:
        component: worker
    spec:
      containers:
        - name: worker
          image: alanlachkar/multi-worker
          env:
            # Name of the ClusterIP linked with redis deployment
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            # Default redis port
            - name: REDIS_PORT
              value: "6379"
